# Joins in MySQL

When we have data split across multiple tables, we use joins to combine that data and get the full picture.

### Let's say we have two tables:

**students**

| id | name  |
|----|-------|
| 1  | Alice |
| 2  | Bob   |

**marks**

| student_id | subject | score |
|------------|---------|-------|
| 1          | Math    | 95    |
| 2          | Math    | 88    |
| 2          | Science | 90    |

---

## 1. INNER JOIN
Include only the rows that have matching values in both tables.
```sql
SELECT students.name, marks.subject, marks.score
FROM students
INNER JOIN marks ON students.id = marks.student_id;
```
Shows only students who have marks recorded.

---
## 2. LEFT JOIN (LEFT OUTER JOIN)
Include all students, even if they don't have any marks.
```sql
SELECT students.name, marks.subject, marks.score
FROM students
LEFT JOIN marks ON students.id = marks.student_id;
```
Useful to list all students and show marks only if available.

---
## 3. RIGHT JOIN (RIGHT OUTER JOIN)
Include all rows from the right table (marks), even if the student is missing.
```sql
SELECT students.name, marks.subject, marks.score
FROM students
RIGHT JOIN marks ON students.id = marks.student_id;
```
Rarely used unless marks exist without a student record.

---
## 4. CROSS JOIN
Combine every row in the first table with every row in the second table.
```sql
SELECT students.name, marks.subject
FROM students
CROSS JOIN marks;
```
Use this only when all combinations are needed.

---
## Summary Table

| Join Type   | What it does                             |
|-------------|-------------------------------------------|
| INNER JOIN  | Only rows with a match in both tables    |
| LEFT JOIN   | All rows from the left table              |
| RIGHT JOIN  | All rows from the right table             |
| CROSS JOIN  | All combinations of rows from both tables |